# Media stack - Kris 22
# 

# .env file variables:
# $PUID
# $PGID
# $TZ i.e. "Europe/London" 
# $DOCKERDIR location of docker and configuration files

# Transmission
#
# LOCAL_NETWORK  CIDR format: i.e. 192.168.1.0/24
# TRANSMISSION_USERNAME anything you like
# TRANSMISSION_PASSWORD anything you like
# MEDIADIR base location for media files, expects subfolders:
# - app_data
# - app_data/downloads
# - app_data/downloads/complete
# - app_data/downloads/incomplete
# - movies
# - tv

# VPN: for config options: https://haugene.github.io/docker-transmission-openvpn/
# VPN_PROVIDER 
# VPN_CONFIG
# VPN_USERNAME
# VPN_PASSWORD

# Stack applications
# [3420]  PLEX
# [9000]  Transmission web UI
# [8888]  Tinyproxy
# [9001]  Jackett
# [9002]  Radarr
# [9003]  Sonarr
# [9004]  Tdarr
# [9005]  Tautulli
# [10000] Portainer agent
# [10001] Ouroboros 

version: "3.7"

services:
  # Portainer: Portainer agent for remote management
  #
  portainer_agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: always
    ports:
      - "10000:9001"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
  # Ouroboros: container management
  #
  ouroboros:
    image: pyouroboros/ouroboros
    container_name: ouroboros
    restart: always
    ports:
      - '10001:8080'
    security_opt:
      - no-new-privileges:true
    environment:
      - CLEANUP=true
      - INTERVAL=86400
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=${TZ}
      - IGNORE="portainer-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # NVIDIA toolkit: Transcoding using NVIDIA hardware.
  #
  # Configure the host with the Nvidia toolkit for NVIDIA transcoding
  # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

  # PLEX: media server
  #
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEXCLAIM} # optional argument
    volumes:
      - ${DOCKERDIR}/app_data/plex:/config
      - ${MEDIADIR}/tv:/tv
      - ${MEDIADIR}/movies:/movies
      - ${MEDIADIR}/transcode:/transcode
      - /etc/localtime:/etc/localtime:ro
  # Transmission: Download client with VPN over IP Vanish
  #
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: unless-stopped
    ports:
      - "9000:9091"
      - "8888:8888"
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1 # Change DNS if needed
      - 1.0.0.1
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=${LOCAL_NETWORK}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*" # Add additional networks as required
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/incomplete
      - WEBPROXY_ENABLED=true # Used to route Jackett traffic
      - WEBPROXY_PORT=8888
    volumes:
      - ${DOCKERDIR}/app_data/transmission:/data
      - ${MEDIADIR}/app_data/downloads/completed:/downloads
      - ${MEDIADIR}/app_data/downloads/incomplete:/incomplete
      - /etc/localtime:/etc/localtime:ro    
  # Jackett: proxy for Radarr and Sonarr
  #
  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    restart: unless-stopped
    ports:
      - "9001:9117"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/app_data/jackett:/config
      - ${DOCKERDIR}/app_data/jackett:/data
      - /etc/localtime:/etc/localtime:ro
  # Radarr: movie downloader
  # 
  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    restart: unless-stopped
    ports:
      - "9002:7878"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - ${DOCKERDIR}/app_data/radarr:/config
      - ${MEDIADIR}/app_data/downloads/completed:/downloads
      - ${MEDIADIR}/movies:/movies
      - /etc/localtime:/etc/localtime:ro
  # Radarr: TV downloader
  # 
  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "9003:8989"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
    volumes:
      - ${DOCKERDIR}/app_data/sonarr:/config
      - ${MEDIADIR}/app_data/downloads/completed:/downloads
      - ${MEDIADIR}/tv:/tv
      - /etc/localtime:/etc/localtime:ro
  # Tdarr: Media transcoder
  #
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9004:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      # Remember to set the below variables before running compose
      #      
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
      - nodeIP=0.0.0.0
      - nodePort=8267 
    volumes:
    - ${DOCKERDIR}/app_data/tdarr/server:/app/server
    - ${DOCKERDIR}/app_data/tdarr/configs:/app/configs
    - ${DOCKERDIR}/app_data/tdarr/logs:/app/logs
    - ${MEDIADIR}:/media
    - ${MEDIADIR}/transcode:/temp
    - /etc/localtime:/etc/localtime:ro
  # Tautulli: PLEX server monitoring
  #
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    ports:
      - "9005:8181"
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/app_data/tautulli:/config
      - ${DOCKERDIR}/app_data/plex:/logs
      - /etc/localtime:/etc/localtime:ro
